name: CLI Test
run-name: ${{ github.actor }} is testing the cli 🧉

on: [push]
jobs:
  linting:
    name: Basic check lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Install packages
        run: |
          python3 -m pip install tox
          mkdir .mypy_cache
      - name: Checking code style
        run: tox run-parallel --skip-env test --parallel-no-spinner

  testing:
    env:
      NUMEXPR_MAX_THREADS: 8
      JUPYTER_PLATFORM_DIRS: 1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          create-args: >
            -c conda-forge
            python=${{ matrix.python-version }}
            tox
            pip
            r-base
            r-essentials
          init-shell: >
            bash
        cache-environment: true
        post-cleanup: 'all'
      - name: Running tests with tox
        run: tox -e test -q
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          slug: FREVA-CLINT/install-kernelspec
          verbose: true
          flags: unittests

  dependabot:
    name: Merge PR by dependabot
    runs-on: ubuntu-latest
    needs: [linting, testing]
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Approve dependabot's PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.TOKEN}}
      - name: Auto-merge for dependabot's PR
        run: gh pr merge --merge --auto "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.TOKEN}}
